version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - moleculer-network
  
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"   
      - "8222:8222"   
    networks:
      - moleculer-network

volumes:
  redis_data:

networks:
  moleculer-network:
    driver: bridge
